server:
  port: 7080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/study_db?serverTimezone=Asia/Seoul
      username: testuser
      password: 1234
      tomcat:
        connection-properties: zeroDateTimeBehavior=convertToNull
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB
      location: static/file
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
# devtools:
#   livereload:
#       enabled: true